### ISSUE TITLE
design async execution architecture

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metadig-engine#102]
Design a new approach to executing metadig jobs that uses asynchronous workers that can be scaled and a reliable job queue.  There would likely be two queues maintained, one called 'pending' which holds the list of jobs to be processed, and one called 'inprocess' for jobs that have been taken by a worker and are being actively processed.

When workers take a job from the pending queue, it is added to the inprocess queue, along with metadata on when processing started.  A reasonable timeout should control whether the controller nixes a job and reissues the job in the pending queue for other workers to pick up.

The queue should be designed such that a worker can crash, and no in progress or pending jobs will be lost.

- [x] Revised Architecture.md page
- [x] Component diagram completed and embedded in architecture page
- [x] Sequence diagrams completed and in architecture page (#103, #104, #105)
- [x] Design mockups completed and in architecture page

**Comment by gothub** [comment]
Last update made in commit 75f0b4125975dc2ba88c104933386bfcb3cd80ea
