### ISSUE TITLE
sequence diagram for trigger to add jobs

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metadig-engine#103]
Design a sequence diagram showing how a trigger event on a MN or CN results in a job being added to the pending queue.

**Comment by gothub** [comment]
This is shown in this [diagram](https://github.com/NCEAS/metadig-engine/blob/master/docs/images/queue-event-trigger_sequence.png)

Updated in commit 75f0b4125975dc2ba88c104933386bfcb3cd80ea

**Comment by mbjones** [comment]
@gothub Let's please discuss this diagram.  I am not following it.
