### ISSUE TITLE
sequence diagram for processing a job

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metadig-engine#104]
Design a sequence diagram showing how a job is picked off of the pending queue by a worker, added to the inprocess queue, processed by the worker, results saved to a Tier 3 node, and then the controller is told the job is complete.

**Comment by gothub** [comment]
This is shown in this [diagram](https://github.com/NCEAS/metadig-engine/blob/master/docs/images/process-queue-entry_sequence.png). 

Updated in commit 75f0b4125975dc2ba88c104933386bfcb3cd80ea

**Comment by gothub** [comment]
Closing

**Comment by gothub** [comment]
hmm, ok now closed
