### ISSUE TITLE
Evaluate use of stand-alone quality Solr server

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#108]
Quality reports can either be indexed in DataONE MN/CN Solr indexes or in a separate Solr index, for example at https://quality.nceas.ucsb.edu/solr.

Pros
- the quality engine can directly send info to the stand-alone server
- no dependency on metacat index releases
- no dependency on DataONE indexing component / CCI releases
- can use Solr releases/features
- easier to update index to add Solr fields
- ???

Cons
- MetacatUI has to query another server for profile reports (DataONE, MN, KNB, group, ...)
- single point of failure unless SolrCloud cluster is setup
- ???

**Comment by gothub** [comment]
@mbjones There hasn't been a log of discussion on this issue specifically, but it has been mentioned a couple of times in the NCEAS dev meetings and in the metadig development meetings that we want to use a standalone Solr server for metadata quality info created by metadig-engine.

I planning on installing a Solr 7.2 server on docker-ucsb-1 with a first pass version of a metadig schema configured, unless this isn't the direction the project should be heading in.

The metadig-worker will be updated to index quality info in this Solr server, from the quality documents that it creates.

The first pass would be to use a single quality instance, but this could be upgraded in the future to use SolrCloud, spread across the k8s cluster nodes or other VMs.

**Comment by mbjones** [comment]
Sounds good, Peter.  I assume you'll deploy this as a kube service, and that it may end up being on any of the nodes that are in the k8s cluster.

**Comment by gothub** [comment]
@mbjones the metdig-worker that sends a generated quality report to the Solr index is planned to be a k8s server. Is that what you are referring to?

The Solr server would be deployed in the usual fashion, as a separate endpoint from the k8s cluster, but potentially on the VMs that we have allocated for the k8s cluster, as those are the machines that are allocated for this project.

If metadig-workers running on the k8s cluster overwhelm the Solr server with insert requests, then the single Solr instance can be incorporated into a SolrCloud that could be spread across the VMs that are also running k8s, or other VMs if they are available (i.e. the existing quality.nceas.ucsb.edu).

**Comment by mbjones** [comment]
No, I am saying that we should try deploying everything needed here as k8s services, and not as a standalone SOLR server. So that would mean deploying SOLR in a manner similar to how you are deoloying RabbitMQ.

**Comment by gothub** [comment]
Ah, ok, understood. My initial thought was that SorlCloud wouldn't work well in k8s as the nodes in a SolrCloud are deliberately configured (i.e. how to split the index across nodes by setting the number of 'shards' for the index), and that having SolrCloud 'nodes' in a k8s cluster being added and removed from the SolrCloud as the workload varies might cause problems and generate a lot of traffic.

However, it looks like there are efforts to setup SolrCloud in k8s (shown [here](https://github.com/mosuka/kubernetes-solr/tree/master/5.5), so it will be interesting to see how SolrCloud performs in k8s.

**Comment by gothub** [comment]
Superseded  by the more specific https://github.com/NCEAS/metadig-engine/issues/166
