### ISSUE TITLE
Fix Travis, CircleCI builds

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#116]
CI builds are failing:

```
testAwardLookup - edu.ucsb.nceas.mdqengine.processor.XMLDialectTest
java
```

This is happening in the feature branch 'controller'.

**Comment by gothub** [comment]
The unit tests now run locally, but there is still a problem with the CircleCI build, which appears to be related to libcurl, as seen from the build log:

```
org.junit.ComparisonFailure: expected:<[true]> but was:<[Error in curl::new_handle() : An unknown option was passed in to libcurl
```
Since the problem appears to be with CircleCI, the build configuration should be updated to version 2.0 first, as version 1.0 is going to be retired this summer, as announced on their website:
```
The CircleCI build/test system that we are using is retiring version 1.0 on August 31, 2018 as
described here.
```
The new configuration has many options for specifying the Docker image to run the tests in,
which may solve the libcurl problem as well as the upgrade requirement.

**Comment by gothub** [comment]
Currently the CircleCI builds have been turned off and I've been trying to get the Travis CI builds working. The difficulty here is that the community edition of Travis currently runs on Ubuntu 14.04, which causes problems for newer versions of R. Travis is planning on moving the community edition projects from travis-ci.org to travis-ci.com and I'm hoping that this will also include an upgrade to the Ubuntu version supported. Here is more info: https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

**Comment by jeanetteclark** [comment]
no longer relevant
