### ISSUE TITLE
Setup persistent volume for k8s

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#124]
Setup a shared filesystem for the k8s cluster that provides
- redundancy 
- failover
- easily scalable

A popular choice is GlusterFS, but this can be a challenge to get running.

The underlying filesystems ('bricks') that comprise the exposed, shared filesystem
could be located on docker-ucsb-1 and docker-ucsb-3, since these VM hosts are on
separate physical hardware.

Requirements before implementing this:
- determine shared filesystem size
  - this maybe be used to support a DBMS used to store quality reports, so could get large
- possibly add more physical storage to the cluster
- create the filesystems

**Comment by gothub** [comment]
Here is a proposed GlusterFS configuration. Partitions on docker-ucsb-1 and docker-ucsb-3 would be available to gluster, with the docker-ucsb-3 partition replicating content from docker-ucsb-1.

docker-ucsb-1, docker-ucsb-3 setup:
- partition: /dev/sdb:
   - filesystem type: ext4
   - size: ? (have to determine what is needed and available)
   - mount point: /data/gluster

gluster volume config:
- bricks included in the disk volume:
   - docker-ucsb-1:/data/gluster/gvol0
   - docker-ucsb-3:/data/gluster/gvol0 (replica of docker-ucsb-1)
- this volume will be available (read, write) to all k8s nodes as `/mnt/glusterfs`

This gluster volume will be made available to the k8s cluster via a [persistent volume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/).

**Comment by gothub** [comment]
Re: disk space needed - here is some information to consider.

DataONE currently has about 250K data packages, and thus 250K metadata documents that are candidates for generating a quality check. (see https://cn.dataone.org/cn/v2/query/solr/?q=*:*&facet=true&facet.field=formatType&rows=0)

As a conservative estimate, say that a typical quality document is between 50K and 200K, that gives us disk usage for storing 'raw' quality reports of between 12.5GB and 45.6GB.

We need to consider how many versions of a document to keep, and typically how many different quality suites might be run on a document.

**Comment by mbjones** [comment]
Let's just go with 500GB for now and see how that works.  I assume we can add more storage later to the glusterfs, right?

**Comment by gothub** [comment]
yes, adding storage is possible, without an interruption of service.

**Comment by nickatnceas** [comment]
I created two new 500GB LUNs on the P2-1 SAN. They're available to the docker VMs at /dev/vdb.

**Comment by gothub** [comment]
@nickatnceas looks great, thanks!

**Comment by gothub** [comment]
The GlusterFS volume `/mnt/gluster` is now available R+W to docker-1, docker-2, docker-3 with this config:

```
slaughter@docker-ucsb-1:~$ sudo gluster volume info gvol0
 
Volume Name: gvol0
Type: Replicate
Volume ID: 3032c1e8-1122-4f86-9044-1624b39ad793
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 2 = 2
Transport-type: tcp
Bricks:
Brick1: docker-ucsb-1.test.dataone.org:/data/gluster/gvol0
Brick2: docker-ucsb-3.test.dataone.org:/data/gluster/gvol0
Options Reconfigured:
transport.address-family: inet
performance.readdir-ahead: on
nfs.disable: on

slaughter@docker-ucsb-1:~$ df -hT | grep /mnt/gluster
docker-ucsb-1.test.dataone.org:/gvol0 fuse.glusterfs  459G   71M  435G   1% /mnt/glusterfs
```
