### ISSUE TITLE
Move 'level' from check to suite

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#126]
Currently the `level` for a check is set in the check xml, for example, in the 'Usage should be Creative Commons' check we have:
```
         ...
        <level>REQUIRED</level>
         ...
```

Move this XML element to the suite xml, so that the suite can set the level of the check, for example, the ADC suite XML would be changed from
```
 <check>
    <id>check.usage.is.cc.1</id>
  </check>
```
to
```
 <check>
    <id level="REQUIRED">check.usage.is.cc.1</id>
  </check>
```

If the `level` is not specified for a check (in the suite xml), then the default `REQUIRED` will be imposed on the check.

This issue was raised during a MetaDIG meeting on 2018 05 02.

**Comment by gothub** [comment]
Currently the levels for a check are restricted to one of "INFO", "OPTIONAL", "REQUIRED".

Should this restriction be removed so that any string can be specified by a suite for each check?

**Comment by amoeba** [comment]
Good change 👍!

On one hand I like the idea of opening it up so the Suite authors can form their own taxonomies but on the other hand I remember that it's super hard to build useful user interfaces without strict taxonomies. i.e. it'd be hard to know when a metadata record complies fully with a Suite unless we encode some semantics here. I think I like the current, restricted taxonomy.

**Comment by gothub** [comment]
Now, if a `<level>` or `<type>` is defined in a suite definition file for a check, it will override the value specified in the check definition file. Changed in commits fd7ca3ddb395a9c36b3fff1b26b593975e2d12fb and e86f6e553b30eca50dd20bb42b1df2cb5b6e94b1
