### ISSUE TITLE
Docker Hub performance problems

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#127]
The performance of Docker Hub has been very poor lately, sometimes taking 10-20 minutes to push an image to a personal repository, and often times with the push failing. Pulls are faster but also can fail often, especially in the late afternoon, Pacific Time. These failures are having an impact on development task turnaround.

@mbjones Could we setup an NCEAS local Docker registry? What machine would host this registry?
This could be limited to just k8s for now, if making this generally available is too much overhead for now.

**Comment by mbjones** [comment]
Yes, we can.  Let's keep it local for now.  What resources are required, and which software stack do you want to use?  If memory serves, the default docker registry was pretty lightweight, and mainly needed enough storage for images.

**Comment by gothub** [comment]
Yes, a local registry can be run directly from a container - https://docs.docker.com/registry/deploying/, without registry browsing or login api, etc. 

One consideration is whether or not to have it behind the firewall or use TLS with authentication tokens. The registry could unsecured for now on docker-ucsb-1, and secured if/when the cluster is configured for TLS.

**Comment by gothub** [comment]
A local [Docker registry](https://docs.docker.com/registry/) is now available from any of the k8s docker  nodes at http://localhost:5000. An example usage for the metadig tomcat image:
```
docker build -t localhost:5000/metadig/metadig-tomcat:dev .
docker push localhost:5000/metadig/metadig-tomcat:dev
```

Then to see the current repositories and the pushed image:

```
curl -X GET http://localhost:5000/v2/_catalog
curl -X GET http://localhost:5000/v2/metadig/metadig-tomcat/tags/list
```
