### ISSUE TITLE
Quality report error on Firefox

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#128]
When generating a quality report on Firefox Quantum 60.0 (64 bit) , the report is not completely created and an error prints to the JS console. The following image shows the section of the report that has a `sonSyntaxError` in the report body, and an `XML Parsing Error` in the JS console:

<img width="1438" alt="screen shot 2018-05-15 at 1 18 08 pm" src="https://user-images.githubusercontent.com/6412946/40081409-babb6798-5842-11e8-9756-0971e3f62193.png">

This error was created for the following URL:

https://arcticdata.io/catalog/#quality/doi%3A10.18739%2FA2BG2H890

**Comment by jeanetteclark** [comment]
I cannot recreate this error anymore
