### ISSUE TITLE
DOI quality check incorrect results

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#133]
The `check.identifier.is.doi.1` check is returning `The identifier looks like a DOI.` when the pid is not a DOI, for example, this result is returned for pid "urn:uuid:f66bf136-9dfd-49a2-8a78-4527481ba8e1"

**Comment by gothub** [comment]
It looks like the issue is that the check looks at the XML element `/eml/@packageId`. This is fine if the convention is to put the DataONE package id in this element. @amoeba is this convention followed for ADC? I don't think this can be counted on for KNB, and there is nowhere else where the D1 package id is typically put. If this is the case, then I propose that this check be removed from the KNB quality suite.

**Comment by amoeba** [comment]
AFAIK the Registry, the new editor, and arcticdatautils all set the packageId to the PID of the metadata Object. So I'd consider that a convention. I'd consider it a good check to match the EML packageId to the PID of the Object but maybe that's another Check.

**Comment by gothub** [comment]
Yeah, good idea - the sysmeta is submitted with the metadata document to the quality engine, so the check can be updated to check that also.

**Comment by gothub** [comment]
Use the metadata pid from the system metadata, if available. Changed in commit e376a405d5379ade45593e39dce517c2bf74a69d
