### ISSUE TITLE
Build Docker images using maven

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#136]
Add the building of the metadig-engine Docker images to the maven build process, to both the package and deploy targets.

Currently the Docker images are built using shell scripts and Dockerfile files, after 'mvn install' has been run.

Product deliverables are saved to https://jitpack.io/#NCEAS/metadig-engine

**Comment by gothub** [comment]
The Docker image 'metadig-worker' can now be built using maven. After `mvn package` or `mvn install`, these commands can be invoked to build and push an image to `docker.io/metadig/metadig-worker`:

```
mvn docker:build
mvn docker:push
```

Note that the `metadig-controller` image is now built from the `metadig-webapp` git repo, as described in https://github.com/NCEAS/metadig-webapp/issues/6

**Comment by amoeba** [comment]
Hey @gothub I'm a bit late to the party here, but have you seen https://cloudplatform.googleblog.com/2018/07/introducing-jib-build-java-docker-images-better.html and is it useful at all here or elsewhere?

**Comment by gothub** [comment]
@amoeba this looks interesting - i'm currently using https://maven.fabric8.io/ which seems to be working fine, but if jib can build faster it could be a better option.

**Comment by amoeba** [comment]
Cool! 👍
