### ISSUE TITLE
Configure a development k8s cluster

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#150]
Allocate resources for and bring up a development k8s cluster. This could be  a single node system.
It would be used for developing k8s configurations and services 

The current k8s that is running on the `docker-ucsb-1,2,3` machines would continue to be the production cluster. The intent is to have this cluster support high availability and fault tolerance to reduce service interruptions as much as possible.

**Comment by mbjones** [comment]
If we turn the current machines into a production cluster, we should rename the hosts so that they are not in the 'test' domain.

**Comment by gothub** [comment]
@mbjones @nickatnceas  what name should we rename the docker-ucsb-* to?

- [ ] quality-1.nceas.ucsb.edu, quality-2.nceas.ucsb.edu, ...
- [ ] metadig-1.nceas.ucdb.edu, metadig-2.nceas.ucsb.edu, ...

Also, should the current `quality.nceas.ucsb.edu` become the development k8s machine, or should that be on different hardware? The k8s development machine should be at least as capable as the current `docker-ucsb-1`, as all development containers would be running on that one machine.

**Comment by mbjones** [comment]
I think keeping their current names but just remove the test domain, e.g., docker-ucsb-1.test.dataone.org would become docker-ucsb-1.dataone.org.

**Comment by gothub** [comment]
The domain names have been updated to `docker-ucsb-1.dataone.org`, `docker-ucsb-2.dataone.org`, `docker-ucsb-3.dataone.org`.

**Comment by gothub** [comment]
The development k8s cluster was installed on Jun 24:
- current nodes: docker-dev-ucsb-1.test.dataone.org, docker-dev-ucsb-2.test.dataone.org
- Ubuntu 18.04.2 LTS
- k8s v1.15.0
