### ISSUE TITLE
Facilitate creation of DataONE quality suite

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#155]
@mbjones has mentioned that the DataONE community has shown interest in helping develop a DataONE metadata quality suite (this was mentioned after the ESA meeting). 

What are the best venues for collaboration to develop this suite (D1 AHM, DUG?, AGU, monthly video conference)? @mbjones @datadavev @csjx @amoeba

This git repo could host a working document that details the suite of checks (similar to the working document LTER had while developing the PASTA checks).

**Comment by gothub** [comment]
Related: https://github.com/NCEAS/metadig-engine/issues/38

**Comment by gothub** [comment]
This topic is on the potential topic list for the DataONE AHM Sep 18-20

**Comment by gothub** [comment]
@scgordon sounds good, let's discuss at the next metadig meeting (DataONE AHM is next week, so 9/19 isn't available).

**Comment by gothub** [comment]
There is currently a `dataone` quality suite that is simply a copy of the KNB suite. This suite only supports EML, as the XPath selectors for checks only exist for EML documents. These should be updated to include selectors for all possible DataONE supported metadata formats. At the DataONE All Hands Meeting last week, it was suggested that the XPaths contained in the sub-processors for the DataONE indexer should be added to the checks, since these XPaths are a mapping between the EML documents and the DataONE Solr index.

@scgordon - could you review these XPaths after I gather them into a Google sheet?

**Comment by gothub** [comment]
A mapping of the XML xpaths to the D1 index fields has already been done! This great resource is available at https://indexer-documentation.readthedocs.io/en/latest/

**Comment by scgordon** [comment]
So then we just need to scrape the xpaths and create giant "or" statements in the xpath element of any check!

**Comment by gothub** [comment]
Yes! Just like your `ACDD_Discovery` suite, for the selector `ResourceIdentifier`:
```
 <xpath>(/MD_Metadata/identificationInfo/*/citation/CI_Citation/identifier/MD_Identifier/code//*) or (/metadata/simpleDc/identifier) or (/*/identifier) or (/*/identificationInfo/*/citation/CI_Citation/identifier/MD_Identifier/code//*) or (/*/DataSetId) or (/*/ShortName | /*/LongName) or (/*/GranuleUR) or (/DIF/Data_Set_Citation/Dataset_DOI) or ( /DIF/Entry_ID/Short_Name) or (/eml/@packageId) or (/resource/identifier | /resource/alternateIdentifiers/alternateIdentifier) or (/metadata/mercury/File_ID) or (/metadata/Local-Control-Number)</xpath>
```

**Comment by gothub** [comment]
See agenda/notes from the MetaDIG [Metadata Metrics workshop](https://docs.google.com/document/d/1ZDk8TylrXfPvtbgMK-XPcRXelnOVpmeS2KUJ9s1w6mQ/edit), including the summary of quality checks for the [DataONE FAIR suite](https://docs.google.com/spreadsheets/d/13bi2C2eZn-Z9KxMm3TuPlBYINSsS20T4W0W7fLRfLc4/edit#gid=431790171&fvid=526924852).
