### ISSUE TITLE
GlusterFS + PostgreSQL fails under heavy loads

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#157]
`metadig-worker` writes generated quality reports to a PostgreSQL database which is stored on a GlusterFS volume. This has worked great during testing, but under not-so-heavy loads (50 workers) writes to GlusterFS fail:

```
ERROR:  unexpected data beyond EOF in block 0 of relation base/16384/16503
HINT:  This has been seen to occur with buggy kernels; consider updating your system.
```
This error occurred for 53 reports written out of 1000 in  a recent test.

A bit of online research shows that this is a [failing of GlusterFS](https://stackoverflow.com/questions/46852123/error-in-performance-test-postgresql-and-glusterfs) not being able to handle database type loads, and not at all due to PostgreSQL.

So, a couple of alternatives are available:
- use a k8s persistent volume, writing to a local disk on a specific cluster node
   - easy to setup
   - no replicaion
- use a k8s persistent volume using CephFS
   - supported by k8s
   - at least one group has tested CephFS under heavy loads with MySQL
   - high availability, redundancy, scalability
   - lots of moving parts
      - ceph_mon, ceph_osd, ceph_mds daemons
   - may require disk partitions to be formatted with XFS (vs ext4 which NCEAS usually uses)
   - requires ceph-fuse module to mount/access the filesystem, i.e. from a shell
- use a k8s persistent volume based on NFS
   - supported by k8s
   - don't know the reliability yet (when used with PostgreSQL/containers)

**Comment by gothub** [comment]
After multiple attempts at installing/configuring/debugging ceph on the k8s cluster using `ceph-deploy`, it is still not working. Each time a different component of the system had problems. I still have faith in this technology, and would like to proceed with evaluation of a k8s container based solution using the [rook orchestration package](https://github.com/rook/rook), currently in beta. Even when ceph is well configured and running, it requires monitoring, which rook provides, with 

However in the meantime, in order to get the k8s cluster backup as soon as possible, i'd like to use NFS, then transition to ceph after it has been fully configured and tested.

@nickatnceas - could you setup an NFS partition using docker-ucsb-1:/dev/vdb, and make this available on docker-ucsb-2, docker-ucsb-3, with whatever disk format you recommend. If you don't have time for this, pls tell me your typical configuration and i'll set it up. (ps - i'm uninstalling ceph within the hour, so that any logical volumes and volume groups setup by ceph will be gone.)

**Comment by nickatnceas** [comment]
I created an EXT4 formatted LVM partition mounted at /data, and setup the NFS server on docker-ucsb-1, sharing /data to docker-ucsb-2 and -3. I used the NFS instructions from https://help.ubuntu.com/16.04/serverguide/network-file-system.html, which are similar to when NCEAS ran NFS v3 some time ago, but now nicely works with NFS v4.

**Comment by gothub** [comment]
The discussion regarding using CephFS is continued [here](https://github.com/NCEAS/metadig-engine/issues/167). NFS is working well in k8s, although a more dynamically scalable solution is desired.
