### ISSUE TITLE
Should ISO namespaces be ignored in check XPath expressions

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#165]
The quality checks currently allow for either ignoring name space prefixes when matching XPaths to documents, or honoring all prefixes. 

Should the checks ignore all namespaces in the documents? This may be most relevant for ISO documents, since each element in a path is typically namespaced, e.g. for sample path from an NCEI document:

```
/gmi:MI_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:lineage/gmd:LI_Lineage/gmd:processStep/gmd:LI_ProcessStep/gmd:description
```

@tedhabermann @mbjone - thoughts?

**Comment by mbjones** [comment]
For a super-specific path like this, namespaces probably add little.  The place where they are helpful is to differentiate when the same local name has different meanings, which is rare.  In the ISO case, there may be good reason to differentiate 19115 and 19115-2 paths and where they may differ. But, in most cases I think you can use just local names and have a more configurable system (ie, more applicable across updated schemas).

**Comment by gothub** [comment]
The general approach now is to not use namespaces, unless it is necessary for a particular check.
The default for checks is to ignore namespaces. Any check selector can be coerced to honor namespaces by using the 'namespaceaware' attribute:

```
<selector namespaceAware="true">
    <name>contactPresent</name>
    <xpath>boolean(/eml:eml/dataset/contact)</xpath>
</selector>
```
