### ISSUE TITLE
Evaluate/implement CephFS for use with k8s metadig-engin

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#167]
GlusterFS doesn't perform well with our k8s cluster as described https://github.com/NCEAS/metadig-engine/issues/157. Currently NFS is being used as a hopefully interim solution. So, continue the evaluation and discovery of an optimal configuration using CephFS for the k8s cluster. This will require having a development cluster for testing, as it's possible that testing could cause problems requiring a system reboot or other service interruptions. Details of the testing will be tracked in this issue.

**Comment by mbjones** [comment]
I'm pretty sure that @gothub  moved this mountpoint from NFS to Ceph and that this task is complete. Let's verify and then the ticket can be closed.
