### ISSUE TITLE
Update build to acquire metadig-checks

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#191]
The new repository `github/NCEAS/metadig-checks` is the new home for authoring and updating metadig-engine checks. Refactor the build process and repo to:
- remove the local copy of suites/checks
- acquire the latest version of checks and suites from metadig-checks

**Comment by mbjones** [comment]
By acquire, what do you mean?  Is this a compile-time acquire, or acquired at runtime?  I think it would be awesome if the admin could choose which suites/checks to install and make available without compiling the system.  For standalone operation, such as in the metadig-r tool, they might be looked for in a standard or configurable directory.  For the kubernetes deploy, they might be mounted in a directory on a shared data volume that is accessible to the engine workers. Or maybe they are exposed as their own pod that can be linked to the worker pods? Do you think something like this could work to allow admins to flexibly deploy and rapidly change which checks are available without a full redeploy?

**Comment by gothub** [comment]
Yes, the suite and check lists should be configurable. The `metadig-engine` is deployed as a Java servlet, so there are some restrictions on where it can read files from (I'll look into this). For k8s, the workers currently read config info from a shared directory, so possibly the suites/checks could be read from there as well.  Metadig-r could read from a configurable location. Currently this package doesn't run suites (just a single check), but adding this capability is on the list.

**Comment by gothub** [comment]
The location of additional checks and suites is now read from the metadig.properties file, so checks and suites can be read directly from disk at runtime.

Updated in commit 7db3c131cd619dd2c9b908ed6f4ca02f33746cf4

The following code was not in the above commit due to a check in error, but the config is read here:
https://github.com/NCEAS/metadig-engine/blob/master/src/main/java/edu/ucsb/nceas/mdqengine/store/InMemoryStore.java#L53
This section of code should have been in the above commit.
