### ISSUE TITLE
Which date to use for aggregated statistics/reports

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#202]
Is the 'dateUploaded' date from sysmeta the correct date to use when calculating aggregated statistics for metadata quality? These dates are used in the Solr index (and later MDC ElasticSearch). There are other dates that can be obtained from metadata, such as 'datePublished'. Should this be used instead?

What are the downsides of using 'dateUploaded'?

**Comment by mbjones** [comment]
I think dateUploaded is the right date, as it reflects when this version was uploaded (IIRC).  datePublished reflects the initial pub date of the data set and is part of the citation, and typically doesn't change.  So, for a dataset that is with `datePublished` set to 2015, but with versions uploaded on `2015-03-01`, `2016-07-01`, and `2017-02-01`, we'd want the statistics for those versions to count in the month in which they were uploaded.

**Comment by gothub** [comment]
OK, thanks for the clarification - what you described regarding 'datePublished' is what I've been using for the aggregated statistics.
