### ISSUE TITLE
Create metadig-engine k8s operations manual

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#246]
This manual should include:

- how to build metadig-engine and metadig-webapp software & Docker containers
- deploying metadig-engine containers/services into k8s
- managing k8s services
- monitoring k8s services 
- troubleshooting k8s services

This is currently low priority task, but should begin soon

**Comment by mbjones** [comment]
Initial operations guide started by @gothub here: https://github.com/NCEAS/metadig-engine/blob/main/docs/operations-manual.md 

I will retarget this issue to 2.5.0 just so we can review for completeness, but this can likely be closed.
