### ISSUE TITLE
Transition to git workflow using 'develop' branch

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#274]
In order to simplify releases, adopt the same git workflow used by [metacatui](https://github.com/NCEAS/metacatui/blob/master/CONTRIBUTING.md).

Although development on metadig-engine doesn't usually involve work on multiple releases at once, this simpler
workflow should be adopted. 

The 'develop' and 'release' branches will be created.

Here is the graphic (from the metacatui repo) which illustrates this workflow:

![nceas-dev-flow](https://user-images.githubusercontent.com/6412946/101671356-3f892000-3a09-11eb-83ae-92457338d1d9.png)

Current work on the dev-2.4 will be completed before this new workflow is used.

**Comment by mbjones** [comment]
This looks good, @gothub . Two minor issues. First, the 1.0.0 tag on master and releases should be the same commit as on develop where it was merged, so it should be shown not as new versions, but rather as straight across. Second, I no longer think that we need a releases branch at all. The `main` branch serves that purpose, and tags can be made directly there. While this applies to metadig, I also think its true of metacat and metacatui and other repos.

**Comment by gothub** [comment]
The `develop` branch will be used going forward, and releases will be tagged from the `main` branch.
