### ISSUE TITLE
Rename the master branch to main

### ISSUE THREAD

**Issue by csjx** [NCEAS/metadig-engine#282]
From an inclusivity perspective, I suggest we rename the `master` branch to `main` and generally use more welcoming terms as we describe our software architectures. The use of the the terms `master` and `slave` in computing are not welcoming.  For context, see the [Inclusive Naming](https://inclusivenaming.org) project and [this repo](https://github.com/github/renaming).

**Comment by gothub** [comment]
@csjx thx for the suggestion. I can rename the branch to `main` when outstanding PRs have been merged.

**Comment by mbjones** [comment]
@gothub GitHub will retarget your PRs, so its easy to do even before you merge any PRs as long as you use the GitHub Settings to rename the branch.

**Comment by gothub** [comment]
@mbjones My github account doesn't have access to the 'Settings' tab. If you have a minute, could you rename the branch?

**Comment by mbjones** [comment]
OK, I renamed the branch. A working copy can be brought up to date with:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by mbjones** [comment]
Also, you should check Travis for any automated builds to be sure they continue to function. We may need to convert any travis-ci.org builds to travis-ci.com.

**Comment by gothub** [comment]
Travis builds have been updated and are passing, since commit 24e37652915cd8848a8b8c7b2d42b10ff2d0ea99
