### ISSUE TITLE
update architecture diagram

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-engine#326]
It would be nice to have a slightly more readable and editable [architecture diagram](https://raw.githubusercontent.com/NCEAS/metadig-engine/main/docs/images/metadig-engine_components.png), particularly as we start to think about how to implement horizontal scaling with data checks.

[PlantUML](https://plantuml.com/) within an .rst doc was suggested, this is what the new metacat diagrams are drawn in

**Comment by mbjones** [comment]
If you want to stick with Markdown, another option might be to use the new Mermaid support from GitHub. I tried it a few months ago and there were some rough edges, but seemed like it was close. Maybe worth another try. 

- GitHub blog about support: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
- Mermaid docs: https://mermaid-js.github.io/mermaid/#/flowchart

A simple example:

```mermaid
graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

**Comment by jeanetteclark** [comment]
new diagrams are all in the docs
