### ISSUE TITLE
Write up a KNB Suite

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metadig-engine#39]
Write up a Suite for the KNB.

**Comment by amoeba** [comment]
This list is a conversion of what's included in the registry form. More checks might be wanted by others, please contribute.

- Title is present
- Creator is present
- Contact is present
- Abstract is present
- Temporal coverage is present (exists + has a start year at least)
- Geographic description is present
- Coordinates are present (either point or box)
- Data Medium is either Digital, Hardcopy, or anything else
- Use Rights is either 'No restrictions', 'Obtain permission from data set owner(s)' or anything else

**Comment by gothub** [comment]
@amoeba Is the KNB suite the one that would support the new editor? Could we just
have a DataONE suite and support a REST call that allows running a single check? Seems like
all the checks you mentioned above would be part of the DataONE suite. Also, what in the
ADC suite wouldn't go into the D1 suite? Hoy, maybe we need an .md file or spreadsheet
for the suites!

**Comment by amoeba** [comment]
Probably a lot of overlap between these suites. Most of the Arctic Data Center Checks would be good candidates for the D1/KNB Suites. A spreadsheet might be a good way to keep them straight in our heads.

We definitely need to discuss running Checks on incomplete documents. I'll add that as a potential use case and we can discuss it.

**Comment by amoeba** [comment]
From our call today, KNB Checks may only really differ in their LEVEL flags.

**Comment by amoeba** [comment]
Using a Google Doc to organize this: https://docs.google.com/spreadsheets/d/1771E8b5PbnyBKKtYYaz-D4GeTqO2WwONI5LndaECe1s

**Comment by gothub** [comment]
@amoeba I'm adding myself to this task, as you are moving off the project, OK?

**Comment by amoeba** [comment]
great, thanks

**Comment by gothub** [comment]
This suite is now in production on KNB, so am calling this done.
