### ISSUE TITLE
Slow down execution of data suite

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-engine#422]
The data suite shouldn't run unless the metadata document and resource map have finished indexing. I'm not positive, but I'm seeing some random "identifier not found on the node" errors with the data quality suite, and I think it is because the package has not finished indexing.

Need to find a mechanism to not run the suite until that indexing has finished

**Comment by mbjones** [comment]
This sounds smart if we are accessing things via the API. If we move to accessing content from the filesystem, I presume this wait is not necessary and we can go ahead with the metadig data runs before indexing completes?

**Comment by jeanetteclark** [comment]
yes for sure not needed when we switch to filesystem access. For now I have a bit of a hack in the first check that runs in the suite that seems to be working ok, and is easily removed when we switch data access mechanisms

```
    data_pids <- NULL
    attempt <- 1
    while(is.null(data_pids) && attempt <=10) {
      attempt <- attempt + 1
      try(data_pids <- get_data_pids(sys@identifier, sys@authoritativeMemberNode))
      Sys.sleep(5)
    }
```

**Comment by mbjones** [comment]
This is a data dependency, and could be expressed as such in a DAG for systems that support that. Run `Z` when `X` and `Y` are available.

**Comment by mbjones** [comment]
In an ideal implementation, MetaDIG would have no dependency on `dataone-indexer`. All of the resources it needs should be available in HashStore locally. As a data package, we can only know the full contents of the data package when the resource map is published. Once you have that, you have in inventory of the files needed for the DAG above, and can implement a proper dependency system.

That said, sometime in the (hopefully) near future, ORE resource maps will be supplemented by other mechanisms to list package contents -- such as metadata associations at the file level. In which case, we won't know the full contents of a package until those files are compiled into a list -- maybe even indexed. So.... this needs some thought and planning as @datadavev proposes storage designs for large packages.

**Comment by jeanetteclark** [comment]
in the meantime, a viable solution (discussed on the backend call) would be to shift from solr querying the `isDocumentedBy` field to directly parsing the resource map. This would entail looking for a corresponding resource map for the most recent metadata pid. if one does not exist, walk back the previous metadata pid and look for it's resource map. once a resource map is found, walk up the version chain to find the most recent one (presumably corresponding to the metadata doc in question). then we would get that object and parse it to get the list of data pids (and the metadata pid, to confirm it is indeed the correct resource map).
