### ISSUE TITLE
Weird error in Arctic suite

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metadig-engine#84]
I've been seeing this for a while but didn't see an Issue for it.

When I run the arctic suite on this document, 

https://arcticdata.io/catalog/#quality/doi%3A10.18739%2FA24805

you see this in the INFO section:

> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 31 path $.output

Not sure what's going on but that shouldn't appear in the report.

**Comment by gothub** [comment]
Fixed in commit e3590f5ae4d24fa302e3f4350226222b32804489
