### ISSUE TITLE
Methods check in arctic suite produces an error

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metadig-engine#85]
When visiting https://arcticdata.io/catalog/#quality/doi%3A10.18739%2FA2WZ4D I see this in the FAILED section:

> Error in strsplit(thisDescr, "\\s+", perl = T) : non-character argument Calls: check -> unlist -> strsplit Execution halted

It looks like it's the Methods present check. We should fix this so this error can't happen.

**Comment by gothub** [comment]
Fixed in commit 795b6e23aa5234489a73283dbe1f0ecbe30d04ca
